apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: <CLUSTERNAME>-infra-internal-uksouth2
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: <CLUSTERNAME>
    machine.openshift.io/cluster-api-machine-role: infra
    machine.openshift.io/cluster-api-machine-type: infra
    infra-segment: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: <CLUSTERNAME>
      machine.openshift.io/cluster-api-machineset: <CLUSTERNAME>-infra-internal-uksouth2
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: <CLUSTERNAME>
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: <CLUSTERNAME>-infra-internal-uksouth2
        infra-segment: internal
    spec:
      taints:
        - key: node-role.kubernetes.io/infra
          value: reserved
          effect: NoSchedule
        - key: node-role.kubernetes.io/infra
          value: reserved
          effect: NoExecute
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
          infra-segment: internal
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1beta1
          kind: AzureMachineProviderSpec
          location: uksouth
          vmSize: Standard_D4s_v3
          vnet: vnet-aro-schiphol
          subnet: snet-infra-internal
          zone: "2"
          image:
            publisher: azureopenshift
            offer: aro4
            sku: aro_415
            type: MarketplaceNoPlan
            version: 415.92.20240220
            resourceID: ""
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          networkResourceGroup: rg-schiphol-network
          osDisk:
            diskSettings: {}
            diskSizeGB: 128
            managedDisk:
              securityProfile:
                diskEncryptionSet: {}
              storageAccountType: Premium_LRS
            osType: Linux
          publicIP: false
          userDataSecret:
            name: worker-user-data
          acceleratedNetworking: true
          resourceGroup: aro-<CLUSTERNAME>-uksouth
          securityProfile:
            settings: {}
          diagnostics: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-internal-node-config
  namespace: openshift-machine-api
data:
  user-data: |
    #cloud-config
    write_files:
      - path: /etc/kubernetes/infra-node-config
        content: |
          INFRA_SEGMENT=internal
          NODE_TYPE=infra
    runcmd:
      - echo "Internal infra node configured"
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: infra
spec:
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values: [worker,infra]
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/infra: ""
  paused: false

